### ISSUE TITLE
Verifying and extracting MasterList failure

### ISSUE THREAD

**Issue by nikolindima** [AndyQ/NFCPassportReader#79]
Hello. I try to use Master list generator but have no success. 
python3 extract.py icaopkd-002-ml-000159.ldif

if i use default Openssl it give me error - The version of OpenSSL you are using doesn't support the CMS command

I try Openssl 1.1.1, 1.0.2s, 1.0.2t versions all with CMS. And every time get error
Verifying and extracting MasterList 11
[Verification failure
140736215831488:error:04091068:rsa routines:int_rsa_verify:bad signature:crypto/rsa/rsa_sign.c:220:
140736215831488:error:2E09809E:CMS routines:CMS_SignerInfo_verify:verification failure:crypto/cms/cms_sd.c:767:
]
Traceback (most recent call last):
  File "extract.py", line 181, in <module>
    main( sys.argv[1] )
  File "extract.py", line 42, in main
    extractCertsFromMasterlist( ml )
  File "extract.py", line 88, in extractCertsFromMasterlist
    raise Exception( "Verification of Masterlist data failed" )
Exception: Verification of Masterlist data failed

I try use Catalina and Sierra - same result

**Comment by nikolindima** [comment]
Fix problem. Need install OpenSSL 1.0.2t  10 Sep 2019
